### ISSUE TITLE
Create frameworks for iOS and OSX

### ISSUE THREAD

**Issue by mike-lischke** [gianlucabertani/Objective-Zip#22]
Make the library a good citizen and add build targets for isOS and OSX frameworks.

**Comment by jflow** [comment]
Dynamic frameworks is really required anymore as you can not mix static libraries and frameworks with CocoaPods. Some pods only work as frameworks. Please support this!!!!!!

**Comment by mike-lischke** [comment]
This is a very old issue and so far nobody took care, so I guess it doesn't makes sense to keep it open. I'm not using Objective-Zip anyway.
