### ISSUE TITLE
OZZip Stream access in Swift 3 Fails

### ISSUE THREAD

**Issue by andyj-at-aspin** [gianlucabertani/Objective-Zip#47]
The most recent change to the Swift 3 language (as delivered in XCode 8 beta 6) has made some further changes to the way ObjectiveC interacts with Swift.

Once the code in Objective-Zip_Swift_Tests.swift has been brought up to "current" Swift syntax, the tests segfault with EXC_BAD_ACCESS (code=-1, address=0x3) on line 143 when the NSData buffer is populated using OZZipReadStream.readData():

            NSLog("Test 1: reading from first file's stream...")
            
            let data1 = NSMutableData(length:256)!
            let bytesRead1 = try read1.readData(withBuffer: data1) <<< FAIL HERE!

This code passed without any issue using XCode 7.3 and Swift 2.x. I really can't help but think there is some link here between the expected return value of 3 (bytes read) and the reported address of 0x3 in the EXC_BAD_ACCESS.

**Comment by andyj-at-aspin** [comment]
Specifically, the 6 functions defined with the clang __attribute__((swift_error(zero_result))) modifier are now producing runtime exceptions that are not trapped by swift do...try...catch.... blocks.

**Comment by andyj-at-aspin** [comment]
I think a switch from zero_result to nonnull_error cleans up the issue in Swift 3 beta and continues to work in Swift 2.x. I've issued a pull request.

**Comment by gianlucabertani** [comment]
Thank you, I really didn't have the time to put my head into this problem. I'll check and pull your request as soon as possible.

**Comment by gianlucabertani** [comment]
Request pulled. Thanks again for your time investigating this issue.
