### ISSUE TITLE
Conflict with OpenSSL

### ISSUE THREAD

**Issue by timautin** [gianlucabertani/Objective-Zip#69]
Hello,

Thanks for your great work!

Since I upgraded to version 1.0.5 from 1.0.3, I'm no longer able to unzip files. I noticed that if I remove the OpenSSL dependency I have (pod 'OpenSSL', '~> 1.0'), it works again. Versions 1.0.4 & 1.0.5 are affected, 1.0.3 works.

The app throws an exception in OZZipReadStream.m at line 81 (in method readDataWithBuffer, result of unzReadCurrentFile is < 0).

When upgrading I noticed that a crypt.c file is added to MiniZip, maybe there's a conflict somewhere in this file with OpenSSL (which has a crypto.h file).

Not sure if you can / want to do something, but please let me know if it is the case.

Thanks!

**Comment by gianlucabertani** [comment]
Sounds strange to me that two pods conflict due to a header file. I will try to reproduce the problem and see what I can do, but can't promise to do it quickly.

**Comment by timautin** [comment]
I agree that it is strange, took a while to figure what was going on. I didn't try on a new project, hopefully you'll be able to reproduce. Do not hesitate to ask if you want me to do some test. No worries for the delay, I'm not in a hurry as version 1.0.3 works fine.

**Comment by timautin** [comment]
FYI, I changed my OpenSSL lib (from pod 'OpenSSL', '~> 1.0' to pod 'OpenSSL-Universal'), and the conflict is gone, I can now use 1.0.5.

**Comment by gianlucabertani** [comment]
Thanks for letting me know. I've been really busy lately, sorry for not finding the time to look into it.

**Comment by timautin** [comment]
No worries, I perfectly understand!
