### ISSUE TITLE
UnZips Successfully Only with B1 Free Archiever

### ISSUE THREAD

**Issue by MohamedJaffer-24** [gianlucabertani/Objective-Zip#75]
Hi . I am also using Objective_Zip Third Party Library to Zip my file in swift . When I try to Zip it with password Protected and then send it via Email or some other source and tried opening it in my mac , It fails to Open .
It Prompts for Password Again and Again (Even the Correct Password is given).
I have attached the file Encrypted File
REDACTED

But I tried opeing the same file using "B1 Free Archiver" , There it opens and unzips successfully . The Problem is why i cant able to open it in "Archive Utility " of my mac . My Mac Os Version - 11.2.3 (BigSur)

**Comment by gianlucabertani** [comment]
Hello. 

I'm afraid this library and project are deprecated, since more than 2 years. You should really switch to a different library.
Best regards.
